### ISSUE TITLE
Leftover text-domain in List Table

### ISSUE THREAD

**Issue by pbrocks** [editorblocks/disable-gutenberg-blocks#1]
Hi there,

Not sure if you're accepting PRs or if this is even worth PRing, but I was stoked to see your List Table and noticed some detritus from a previous project. I've updated `disable-google-fonts` on [my repo here](https://github.com/SidetrackStudio/disable-gutenberg-blocks/tree/fix/text-domain-update). I am thinking I'd like to add some sorting to the table, though, and maybe that's a better PR, if you're open to that. Either way, FYI on the text domain.

**Comment by DannyCooper** [comment]
Hi @pbrocks,

Good spot - thanks for that!

Yes, I'd love to see a PR based on sorting the blocks.

Thanks

**Comment by DannyCooper** [comment]
Fixed in https://github.com/editorblocks/disable-gutenberg-blocks/commit/df85328e4df4331ad000c39b5c2a860ac6c20856

**Comment by pbrocks** [comment]
Looking deeper into this the sorting will be difficult since this is pulled into JS territory and therefore we won't be able to use the native tools. Looking now at one proposed avenue https://twitter.com/aaronjorbin/status/1072892635952676864

**Comment by DannyCooper** [comment]
That does look interesting. A simpler initial route could be to add a search `<input>` or category `<select>` then filter the `blocks` var `onChange()`.
